### PR TITLE
Create license-activation.md

### PR DESCRIPTION
**Pull request by Eric-revollo**
@niharsawant  @sikrigagan  please review

### CODE REVIEW

**Comment by niharsawant** [comment]
@sikrigagan and @Eric-revollo I have added additional info. Please have a look. If all is good then we will go ahead and merge with `stage`

**Comment by Eric-revollo** [comment]
I think all looks good

**Review by sikrigagan — APPROVED** [review]

**Review by sikrigagan — APPROVED** [review]
We'll add it to sidebar while doing the public release.

**Comment by sikrigagan** [comment]
@Eric-revollo Everything looks good to me. You can push it to stage so that we can check it on test server before pushing it live. Let's target making this page live by tomorrow.
@niharsawant FYI

**Review by niharsawant — APPROVED** [review]

**Comment by niharsawant** [comment]
Here is the link:
http://paradocs.fusioncharts.net/dev/upgrading/license-activation. We will
deploy it on production tomorrow morning IST.

**Pull request merged**
